version: "3.8"
services:
  payment-gateway:
    build: ./payment-gateway
    env_file:
      - .env
    environment:
      WEBHOOK_HOST: app
  app:
    build: ./payment-engine
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - payment-gateway
    env_file:
      - .env
    environment:
      DB_HOSTNAME: postgres
      PAYMENT_HOST: payment-gateway
  postgres:
    image: postgres:14.11
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "5433:5432" # I USED 5433 TO AVOID CONFLICT WITH LOCAL POSTGRES
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
